package alAssistance;

import okhttp3.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class AIService {

	 private static final String API_URL = "https://api.openai.com/v1/chat/completions";
	    private static final String API_KEY = ConfigLoader.getProperty("openai.api.key");

	    /**
	     * 🔥 Generates Selenium TestNG test cases using ChatGPT and saves them as a Java class in the project.
	     * @param prompt The description of the test cases.
	     * @param className The name of the Java test class to be generated.
	     * @param packageName The package path where the test class should be saved.
	     * @throws IOException if there is any I/O or API communication issue.
	     */
	    public void generateTestClass(String prompt, String className, String packageName) throws IOException {
	        OkHttpClient client = new OkHttpClient();
	        ObjectMapper objectMapper = new ObjectMapper();

	        // 🔄 Create request payload
	        Map<String, Object> requestBody = new HashMap<>();
	        requestBody.put("model", "gpt-3.5-turbo");
	        requestBody.put("messages", new Object[]{Map.of("role", "user", "content", prompt)});

	        String jsonRequest = objectMapper.writeValueAsString(requestBody);

	        RequestBody body = RequestBody.create(jsonRequest, MediaType.parse("application/json"));
	        Request request = new Request.Builder()
	                .url(API_URL)
	                .post(body)
	                .addHeader("Authorization", "Bearer " + API_KEY)
	                .addHeader("Content-Type", "application/json")
	                .build();

	        try (Response response = client.newCall(request).execute()) {
	            if (!response.isSuccessful()) {
	                throw new IOException("❌ API call failed: " + response.code() + " - " + response.body().string());
	            }

	            // 🎯 Extract generated code
	            JsonNode jsonNode = objectMapper.readTree(response.body().string());
	            String generatedCode = jsonNode.get("choices").get(0).get("message").get("content").asText();

	            // 💾 Save the generated test case to correct package structure
	            saveTestCaseToProject(generatedCode, className, packageName);
	        }
	    }

	    /**
	     * 💾 Saves the generated test case code into the proper package structure.
	     * @param code The Java code generated by ChatGPT.
	     * @param className The Java class name (without extension).
	     * @param packageName The package path for the class.
	     * @throws IOException if there is any issue during file creation.
	     */
	    private void saveTestCaseToProject(String code, String className, String packageName) throws IOException {
	        String projectRoot = "src/test/java/";  // Adjust if your test directory differs
	        String packagePath = packageName.replace(".", "/");
	        File directory = new File(projectRoot + packagePath);

	        if (!directory.exists() && directory.mkdirs()) {
	            System.out.println("📁 Created package directory: " + directory.getAbsolutePath());
	        }

	        String filePath = projectRoot + packagePath + "/" + className + ".java";
	        try (FileWriter writer = new FileWriter(filePath)) {
	            writer.write("package " + packageName + ";\n\n" + code);
	            System.out.println("✅ Test class generated and saved at: " + filePath);
	        }
	    }
}